version: '3.8'

services:
  urlshortener:
    build: ./
    image: urlshortener:latest
    environment:
      DB_URL: 51.250.8.27
      DB_USER: urlshortener
      DB_PASS: urlshortener
      DB_NAME: urlshortener
    ports:
      - "8080:8080"